#!/usr/bin/perl

use 5.030 ; use warnings ; 
use Getopt::Std ; 
use Term::ANSIColor qw [ :constants ] ; $Term::ANSIColor::AUTORESET = 1 ;
use List::Util qw[ min ] ; 
use POSIX qw [ floor ceil ] ;
use Time::HiRes qw[ gettimeofday tv_interval ]; 
my $t0 = [gettimeofday] ;
my @argv = @ARGV ;
getopts '5c:d:f:p:' , \my%o ; 

# テストはここに書く。
if ( exists $o{T} ) { 
  my $cmd = '' ; 
  do { 
    no warnings 'experimental::smartmatch' ; 
  } for $o{T} ;
  system $cmd ; 
  exit ;
}

# 終了時の動作はここに書く。
END{ 
  exit if exists $o{T} ;
  exit if 0 eq ($o{2}//'') ; 
  #say STDERR RED BOLD FAINT "The elapsed second = " .tv_interval ($t0) ;
}

# ここから通常の動作部分。
$o{F} = 1 unless $o{D} || $o{X} ; 
$o{c} //= '' ;   # 値の間に挟む区切り文字
$o{d} //= 1 ; # 10 ** $o{d} の数が最大となる(10の何乗まで調べるのか;主に何桁の分母について調べるのか)
$o{p} //= 'f' ; # 表頭と表側以外の表中に、どんな値を並べるか?
my $u10 = 10 ** $o{d} ; 
$o{f} //= "1,$u10" ; # 開始する最小の分母
my $emp = ' ' x $o{d} ;
say join $o{c} , '-' x $o{d} ,' ' , map { sprintf "%0$o{d}d" , $_ } 1 .. ( $o{5} ? $u10 *0.5 : $u10 - 1 ) ; 

for my $den ( 2 .. $u10 ) { 
  my @f ; 
  for ( 1 .. ( $o{5} ? $den * 0.5 : $den -1) ) {  
    my $fig = int 0.5 + $u10 * $_ / $den ; # 分子の数値
    $f [ $fig ] =  $o{p}eq'X'?'X'x$o{d} : sprintf "%0$o{d}d" , $o{p}=~/n/i ? $_  : $fig ;
  }
  my @out ; 
  push @out , sprintf "%0$o{d}d" , $den == $u10 ? 0 : $den ; 
  push @out , ':' ; 
  push @out , map { $_ // $emp } do { shift @f ; @f } ;
  say join $o{c} , @out ;
}

exit ;

sub VERSION_MESSAGE {}
sub HELP_MESSAGE {
  use FindBin qw[ $Script ] ;
  $ARGV[1] //= '' ;
  open my $FH , '<' , $0 ;
  while(<$FH>){
    s/\$0/$Script/g ;
    print $_ if $ARGV[1] eq 'opt' ? m/^\ +\-/ : s/^=head1// .. s/^=cut// ;
  }
  close $FH ;
  exit 0 ;
}


=encoding utf8

=head1

  $0 [-d 1]  # figdennom が当初のコマンド名

   横に fig 、縦にden 
   色つきで 該当する分子(nom)を表示。


  オプション: 
   -d d : 対象となる分母の値が 1 から 10**d となる。(dは数値)
   # -f n1[,n2] : n1 から n2 まで調べる。 未実装。

   -5 : FIG (小数点以下の数) を横方向に並べるのに、上限を最大の10 ** d - 1 にはせず、その半分にちかい 10 ** d * 0.5 にする。
   -p char : 表頭と表側以外の表中に、どんな値を並べるかを指定。nで分子の値。XでXをd桁並べる。未指定なら四捨五入した小数点以下の値。
 
  使用例: 

  開発メモ: 
    * 対象となる分母の値が 1 から 10**d * 0.5 までにするか、10**d までにするかが、出力で一貫していない。オプションで指定できるようにしたい。

=cut
