#!/usr/bin/perl
use 5.030 ; use warnings ; 
use Getopt::Std ; 
use Term::ANSIColor qw [ :constants ] ; $Term::ANSIColor::AUTORESET = 1 ;
use Time::HiRes qw[ gettimeofday tv_interval ]; 
my $t0 = [gettimeofday] ;
my @argv = @ARGV ;
getopts '.:5c:d:f:l:p:' , \my%o ; 

# テストはここに書く。
if ( exists $o{T} ) { 
  my $cmd = '' ; 
  do { 
    no warnings 'experimental::smartmatch' ; 
  } for $o{T} ;
  system $cmd ; 
  exit ;
}

# 終了時の動作はここに書く。
END{ 
  exit if exists $o{T} ;
  exit if 0 eq ($o{2}//'') ; 
  #say STDERR RED BOLD FAINT "The elapsed second = " .tv_interval ($t0) ;
}

# ここから通常の動作部分。
my $p = $o{'.'} eq 0 ? '' : '.' ;
$o{c} //= ' ' ;   # 値の間に挟む区切り文字
$o{d} //= 1 ; # 10 ** $o{d} の数が最大となる(10の何乗まで調べるのか;主に何桁の分母について調べるのか)
$o{p} //= 'f' ; # 表頭と表側以外の表中に、どんな値を並べるか?
my $u10 = 10 ** $o{d} ; 
$o{f} //= "1,$u10" ; # 開始する最小の分母
my $emp = ' ' x ( $o{d} + ( $o{'.'} eq 0 ? 0 : 1 ) ) ;
my $dz = $o{5} ? $u10 *0.5 : $u10 - 1 ; # 出力の横方向の最後の数

say join $o{c} , '-' x ($o{d}+1) ,' ' , map { sprintf "$p%0$o{d}d" , $_ } 1 .. $dz ; # 表頭
for my $den ( 2 .. $u10 ) { 
  my @f ; 
  $f [ $dz ]  = undef ;
  for ( 1 .. ( $o{5} ? $den * 0.5 : $den -1) ) {  
    my $fig = int 0.5 + $u10 * $_ / $den ; # 小数点以下の数値。
    $f [ $fig ] =  $o{p} eq 'X' ? 'X' x $o{d} : sprintf "$p%0$o{d}d" , $o{p}=~/n/i ? $_  : $fig ;
  }
  my @out ; 
  push @out , sprintf "%".($o{d}+1)."d" , $den ; 
  push @out , ':' ; 
  push @out , map { $_ // $emp } do { shift @f ; @f } ;
  my $str = join $o{c} , @out ;
  say exists $o{l} && ($den+1) % $o{l} <= 1 ? UNDERLINE $str : $str ; 
}

exit ;

sub VERSION_MESSAGE {}
sub HELP_MESSAGE {
  use FindBin qw[ $Script ] ;
  $ARGV[1] //= '' ;
  open my $FH , '<' , $0 ;
  while(<$FH>){
    s/\$0/$Script/g ;
    print $_ if $ARGV[1] eq 'opt' ? m/^\ +\-/ : s/^=head1// .. s/^=cut// ;
  }
  close $FH ;
  exit 0 ;
}


=encoding utf8

=head1

  $0 [-d 1]  # figdennom が当初のコマンド名

   横に fig 、縦にden 
   色つきで 該当する分子(nom)を表示。


  オプション: 
   -d d : 対象となる分母の値が 1 から 10**d となる。(dは数値)
   # -f n1[,n2] : n1 から n2 まで調べる。 未実装。
   -l N : N 行ごとに下線で挟む。
   -p char : 表頭と表側以外の表中に、どんな値を並べるかを指定。nで分子の値。XでXをd桁並べる。未指定なら四捨五入した小数点以下の値。
   -5 : FIG (小数点以下の数) を横方向に並べるのに、上限を最大の10 ** d - 1 にはせず、その半分にちかい 10 ** d * 0.5 にする。
   -. 0 : ピリオドを省略する。


 
  使用例: 

  開発メモ: 
    * 分母が50または500の前後の場合に、同じ割合近似値の出現が多いので、それはなぜかを考察するのが、このコマンドの作成の目的。
    * その50の前後で、出力に並べる数に色を付けたかった。50より後(または前)で初めて出現した回数が少ない値に色を付けたかった。6段階で。
    * 50 の所に横の棒状の蛍光灯があって、それより上の数値は黄色、それより下の数値はシアン色の半透明の物体があって、光を乱反射する様子を見せたかった。

=cut
