#!/usr/bin/perl

use 5.030 ; use warnings ; 
use Getopt::Std ; getopts ':av:o:' , \my%o ; 
use Term::ANSIColor qw [ :constants ] ; $Term::ANSIColor::AUTORESET = 1 ;
use List::Util qw[ min sum sum0 ] ; 
use POSIX qw [ floor ceil ] ;
use Math::Random::MT qw[ rand ] ;

$o{v} //= 10 ; # どの値まで追跡するか 〜$o{v}
$o{o} //= 1 ; # offset 
while ( <> ) { 
  chomp ; 
  my @F = split /\t/ , $_ , 0 ; 
  my $denom = shift @F ; # 最も左の要素を取り出す。
  my @fq ; # 単純に頻度表 を格納。
  $fq [ $_[0] ] = $_[1] while  @_ =  splice @F ,0, 2 ;
  my $avg =  (sum0 map{ $_ * ($fq[$_]//0) } 0..$#fq) / (sum0 grep $_, @fq) if $o{a} ;
  my $oversum = sum0 grep $_, @fq [ $o{v} + 1 .. $#fq ] ;
  my @out = map $fq[$_]//0 , $o{o} .. $o{v} + $o{o} - 1  ; # < 
  unshift @out , sprintf '%6.3f' , $avg + $o{o} if $o{a} ; # < 
  unshift @out , $denom if $o{':'} ; # -: により分母の数を左端に挿入。
  say join "\t" , @out , $oversum ; # <- - 0から
}
exit ;

sub VERSION_MESSAGE {}
sub HELP_MESSAGE {
  use FindBin qw[ $Script ] ;
  $ARGV[1] //= '' ;
  open my $FH , '<' , $0 ;
  while(<$FH>){
    s/\$0/$Script/g ;
    print $_ if $ARGV[1] eq 'opt' ? m/^\ +\-/ : s/^=head1// .. s/^=cut// ;
  }
  close $FH ;
  exit 0 ;
}


=encoding utf8

=head1

  $0 
    もう一つのプログラム(repro)の出力をR言語で処理しやすいように、整形する。
    den v1 f[v1] v2 f[v2] v3 f[v3] .. となっているところを
    f[1] f[2] ... f[$o{v}] sum_{i>$o{v}} f[i] に変換。

    (-o0指定により0始まりが指定されたらf[0] f[2] ... f[$o{v}-1] sum_{i>$o{v}-1} f[i] に変換。)

  オプション: 
    -o N : 未指定なら1。「何番目であるか」をN始まりにする。作成当初は0で対応していたためのオプション。
    -v N  : 1からN番目まではそれぞれの値。それ以上(N+1)以上は合算。
    -a : 平均を算出。
    -: ; 分母を最も左の列に挿入。

  開発上のメモ: 
    もうひとつ、行末にタブ文字が入っていて混乱。
    ※ 尤度の考え方をいろいろ考え中。ある分母において、2番目に来たら、その尤度は低いとかって判断して良いのだろうか?

=cut
